class Agent():
    def __init__(self,
                 obs_shape: tuple,
                 a_shape: tuple,
                 n_frames: int, # how many frames to stack

                ):
        pass


        # self.pre_process = ...
        # self.frame_stack = ...
        # self.crop = ...
        # self.feature_encoder = ...
        # self.sac = ...

        # optimizers ...

